name: PR

on:
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "assets/**"

jobs:
  demo-debug:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Assemble Debug"
        run: ./gradlew :demo:assembleDebug --no-daemon
      - name: "Upload Debug APK to GitHub"
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: demo/build/outputs/apk/debug/demo-debug.apk
  release-demo-app:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Generate Release APK"
        run: ./gradlew :demo:assembleRelease --no-daemon
      - name: "Sign Android release"
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: demo/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: "Upload Release APK to GitHub"
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: demo/build/outputs/apk/release/demo-release.apk
  launcher-debug:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Assemble Debug"
        run: ./gradlew :launcher:assembleDebug --no-daemon
      - name: "Upload Debug APK to GitHub"
        uses: actions/upload-artifact@v3
        with:
          name: Debug APK
          path: demo/build/outputs/apk/debug/launcher-debug.apk
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Lint"
        run: ./gradlew lint --no-daemon
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Dekekt"
        run: ./gradlew detekt --no-daemon
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Test"
        run: ./gradlew test --no-daemon
  lib-api-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
      - name: "Setup Java 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Check API"
        run: ./gradlew :metro:apiCheck --no-daemon
